/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BuilderImport } from './routes/builder'
import { Route as AuthImport } from './routes/_auth'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as BuilderIndexImport } from './routes/builder/index'
import { Route as BuilderEscapeRoomIndexImport } from './routes/builder/escape-room/index'
import { Route as BuilderEscapeRoomNewImport } from './routes/builder/escape-room/new'

// Create Virtual Routes

const AuthSignupLazyImport = createFileRoute('/_auth/signup')()
const AuthLoginLazyImport = createFileRoute('/_auth/login')()

// Create/Update Routes

const BuilderRoute = BuilderImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BuilderIndexRoute = BuilderIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderRoute,
} as any)

const AuthSignupLazyRoute = AuthSignupLazyImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/signup.lazy').then((d) => d.Route))

const AuthLoginLazyRoute = AuthLoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/login.lazy').then((d) => d.Route))

const BuilderEscapeRoomIndexRoute = BuilderEscapeRoomIndexImport.update({
  id: '/escape-room/',
  path: '/escape-room/',
  getParentRoute: () => BuilderRoute,
} as any)

const BuilderEscapeRoomNewRoute = BuilderEscapeRoomNewImport.update({
  id: '/escape-room/new',
  path: '/escape-room/new',
  getParentRoute: () => BuilderRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupLazyImport
      parentRoute: typeof AuthImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexImport
      parentRoute: typeof BuilderImport
    }
    '/builder/escape-room/new': {
      id: '/builder/escape-room/new'
      path: '/escape-room/new'
      fullPath: '/builder/escape-room/new'
      preLoaderRoute: typeof BuilderEscapeRoomNewImport
      parentRoute: typeof BuilderImport
    }
    '/builder/escape-room/': {
      id: '/builder/escape-room/'
      path: '/escape-room'
      fullPath: '/builder/escape-room'
      preLoaderRoute: typeof BuilderEscapeRoomIndexImport
      parentRoute: typeof BuilderImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthSignupLazyRoute: typeof AuthSignupLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthSignupLazyRoute: AuthSignupLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BuilderRouteChildren {
  BuilderIndexRoute: typeof BuilderIndexRoute
  BuilderEscapeRoomNewRoute: typeof BuilderEscapeRoomNewRoute
  BuilderEscapeRoomIndexRoute: typeof BuilderEscapeRoomIndexRoute
}

const BuilderRouteChildren: BuilderRouteChildren = {
  BuilderIndexRoute: BuilderIndexRoute,
  BuilderEscapeRoomNewRoute: BuilderEscapeRoomNewRoute,
  BuilderEscapeRoomIndexRoute: BuilderEscapeRoomIndexRoute,
}

const BuilderRouteWithChildren =
  BuilderRoute._addFileChildren(BuilderRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/builder': typeof BuilderRouteWithChildren
  '/login': typeof AuthLoginLazyRoute
  '/signup': typeof AuthSignupLazyRoute
  '/builder/': typeof BuilderIndexRoute
  '/builder/escape-room/new': typeof BuilderEscapeRoomNewRoute
  '/builder/escape-room': typeof BuilderEscapeRoomIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof AuthLoginLazyRoute
  '/signup': typeof AuthSignupLazyRoute
  '/builder': typeof BuilderIndexRoute
  '/builder/escape-room/new': typeof BuilderEscapeRoomNewRoute
  '/builder/escape-room': typeof BuilderEscapeRoomIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRoute
  '/_auth': typeof AuthRouteWithChildren
  '/builder': typeof BuilderRouteWithChildren
  '/_auth/login': typeof AuthLoginLazyRoute
  '/_auth/signup': typeof AuthSignupLazyRoute
  '/builder/': typeof BuilderIndexRoute
  '/builder/escape-room/new': typeof BuilderEscapeRoomNewRoute
  '/builder/escape-room/': typeof BuilderEscapeRoomIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/builder'
    | '/login'
    | '/signup'
    | '/builder/'
    | '/builder/escape-room/new'
    | '/builder/escape-room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/signup'
    | '/builder'
    | '/builder/escape-room/new'
    | '/builder/escape-room'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/builder'
    | '/_auth/login'
    | '/_auth/signup'
    | '/builder/'
    | '/builder/escape-room/new'
    | '/builder/escape-room/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRouteWithChildren
  BuilderRoute: typeof BuilderRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRouteWithChildren,
  BuilderRoute: BuilderRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/_auth",
        "/builder"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/signup"
      ]
    },
    "/builder": {
      "filePath": "builder.tsx",
      "children": [
        "/builder/",
        "/builder/escape-room/new",
        "/builder/escape-room/"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.lazy.tsx",
      "parent": "/_auth"
    },
    "/builder/": {
      "filePath": "builder/index.tsx",
      "parent": "/builder"
    },
    "/builder/escape-room/new": {
      "filePath": "builder/escape-room/new.tsx",
      "parent": "/builder"
    },
    "/builder/escape-room/": {
      "filePath": "builder/escape-room/index.tsx",
      "parent": "/builder"
    }
  }
}
ROUTE_MANIFEST_END */
