/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as BuilderImport } from './routes/builder'
import { Route as AuthImport } from './routes/_auth'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as BuilderEscapeRoomIdImport } from './routes/builder/$escapeRoomId'
import { Route as DashboardEscapeRoomIndexImport } from './routes/dashboard/escape-room/index'
import { Route as DashboardEscapeRoomNewImport } from './routes/dashboard/escape-room/new'

// Create Virtual Routes

const AuthSignupLazyImport = createFileRoute('/_auth/signup')()
const AuthLoginLazyImport = createFileRoute('/_auth/login')()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const BuilderRoute = BuilderImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const AuthSignupLazyRoute = AuthSignupLazyImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/signup.lazy').then((d) => d.Route))

const AuthLoginLazyRoute = AuthLoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/login.lazy').then((d) => d.Route))

const BuilderEscapeRoomIdRoute = BuilderEscapeRoomIdImport.update({
  id: '/$escapeRoomId',
  path: '/$escapeRoomId',
  getParentRoute: () => BuilderRoute,
} as any)

const DashboardEscapeRoomIndexRoute = DashboardEscapeRoomIndexImport.update({
  id: '/escape-room/',
  path: '/escape-room/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardEscapeRoomNewRoute = DashboardEscapeRoomNewImport.update({
  id: '/escape-room/new',
  path: '/escape-room/new',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/builder/$escapeRoomId': {
      id: '/builder/$escapeRoomId'
      path: '/$escapeRoomId'
      fullPath: '/builder/$escapeRoomId'
      preLoaderRoute: typeof BuilderEscapeRoomIdImport
      parentRoute: typeof BuilderImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupLazyImport
      parentRoute: typeof AuthImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/escape-room/new': {
      id: '/dashboard/escape-room/new'
      path: '/escape-room/new'
      fullPath: '/dashboard/escape-room/new'
      preLoaderRoute: typeof DashboardEscapeRoomNewImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/escape-room/': {
      id: '/dashboard/escape-room/'
      path: '/escape-room'
      fullPath: '/dashboard/escape-room'
      preLoaderRoute: typeof DashboardEscapeRoomIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthSignupLazyRoute: typeof AuthSignupLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthSignupLazyRoute: AuthSignupLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BuilderRouteChildren {
  BuilderEscapeRoomIdRoute: typeof BuilderEscapeRoomIdRoute
}

const BuilderRouteChildren: BuilderRouteChildren = {
  BuilderEscapeRoomIdRoute: BuilderEscapeRoomIdRoute,
}

const BuilderRouteWithChildren =
  BuilderRoute._addFileChildren(BuilderRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEscapeRoomNewRoute: typeof DashboardEscapeRoomNewRoute
  DashboardEscapeRoomIndexRoute: typeof DashboardEscapeRoomIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEscapeRoomNewRoute: DashboardEscapeRoomNewRoute,
  DashboardEscapeRoomIndexRoute: DashboardEscapeRoomIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/builder': typeof BuilderRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/builder/$escapeRoomId': typeof BuilderEscapeRoomIdRoute
  '/login': typeof AuthLoginLazyRoute
  '/signup': typeof AuthSignupLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/escape-room/new': typeof DashboardEscapeRoomNewRoute
  '/dashboard/escape-room': typeof DashboardEscapeRoomIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/builder': typeof BuilderRouteWithChildren
  '/builder/$escapeRoomId': typeof BuilderEscapeRoomIdRoute
  '/login': typeof AuthLoginLazyRoute
  '/signup': typeof AuthSignupLazyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/escape-room/new': typeof DashboardEscapeRoomNewRoute
  '/dashboard/escape-room': typeof DashboardEscapeRoomIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRoute
  '/_auth': typeof AuthRouteWithChildren
  '/builder': typeof BuilderRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/builder/$escapeRoomId': typeof BuilderEscapeRoomIdRoute
  '/_auth/login': typeof AuthLoginLazyRoute
  '/_auth/signup': typeof AuthSignupLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/escape-room/new': typeof DashboardEscapeRoomNewRoute
  '/dashboard/escape-room/': typeof DashboardEscapeRoomIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/builder'
    | '/dashboard'
    | '/builder/$escapeRoomId'
    | '/login'
    | '/signup'
    | '/dashboard/'
    | '/dashboard/escape-room/new'
    | '/dashboard/escape-room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/builder'
    | '/builder/$escapeRoomId'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/dashboard/escape-room/new'
    | '/dashboard/escape-room'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/builder'
    | '/dashboard'
    | '/builder/$escapeRoomId'
    | '/_auth/login'
    | '/_auth/signup'
    | '/dashboard/'
    | '/dashboard/escape-room/new'
    | '/dashboard/escape-room/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRouteWithChildren
  BuilderRoute: typeof BuilderRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRouteWithChildren,
  BuilderRoute: BuilderRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/_auth",
        "/builder",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/signup"
      ]
    },
    "/builder": {
      "filePath": "builder.tsx",
      "children": [
        "/builder/$escapeRoomId"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/",
        "/dashboard/escape-room/new",
        "/dashboard/escape-room/"
      ]
    },
    "/builder/$escapeRoomId": {
      "filePath": "builder/$escapeRoomId.tsx",
      "parent": "/builder"
    },
    "/_auth/login": {
      "filePath": "_auth/login.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.lazy.tsx",
      "parent": "/_auth"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/escape-room/new": {
      "filePath": "dashboard/escape-room/new.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/escape-room/": {
      "filePath": "dashboard/escape-room/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
